version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    target-branch: "RHIN-11743/dep"